### ISSUE TITLE
error when trying to create an http proxy

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/digital_me#18]
gateway deployed with:
```python
data = {
    'nodeId': 'XXXX',
    'hostname': 'zaibongw',
    'domain': 'lan',
    'networks': [{
        'name': 'private',
        'type': 'zerotier',
        'public': False,
        'id': 'XXXX',
        'ztClient': 'ztDev'
    }],
}

dmgw = robot.services.find_or_create('github.com/jumpscale/digital_me/gateway/0.0.1', service_name='gwpriv', data=data)
# install
t = dmgw.schedule_action('install')
```

trying to add http proxy with:
```python
gw.schedule_action('add_http_proxy',args={'proxy':{'name':'web1','host':'gw3.zaibon.be','types':['http','https'],'destinations':[{'vm':'vm1','port':8000}]}})
```

then got this error
```
In [22]: t.eco
Out[22]: Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-templates/templates/gateway/gateway.py", line 116, in add_http_proxy
    self._gateway_sal.configure_http()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/gateway/gateway.py", line 454, in configure_http
    httpserver.apply_rules()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/gateway/http.py", line 28, in apply_rules
    raise RuntimeError("Failed to start caddy server: {} {} {}".format(result.stderr, result.stdout, result.data))
RuntimeError: Failed to start caddy server: 2018/06/28 10:28:21 get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
 Activating privacy features...
Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://acme-v01.api.letsencrypt.org/terms
Please enter your email address so you can recover your account if needed.
You can leave it blank, but you'll lose the ability to recover your account.
Email address:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 77, in execute
    self._result = self._func(**self._args)
  File "/opt/code/github/zero-os/0-templates/templates/gateway/gateway.py", line 120, in add_http_proxy
    self._gateway_sal.configure_http()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/gateway/gateway.py", line 454, in configure_http
    httpserver.apply_rules()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/gateway/http.py", line 28, in apply_rules
    raise RuntimeError("Failed to start caddy server: {} {} {}".format(result.stderr, result.stdout, result.data))
RuntimeError: Failed to start caddy server: 2018/06/28 10:28:52 get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
 Activating privacy features...
Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://acme-v01.api.letsencrypt.org/terms
Please enter your email address so you can recover your account if needed.
You can leave it blank, but you'll lose the ability to recover your account.
Email address:

Failed to start caddy server: 2018/06/28 10:28:52 get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
 Activating privacy features...
Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://acme-v01.api.letsencrypt.org/terms
Please enter your email address so you can recover your account if needed.
You can leave it blank, but you'll lose the ability to recover your account.
Email address:
```

**Comment by zaibon** [comment]
Currently there is a problem with IPV6 and caddy. disabling IPV6 in the netns of the gateway container solve the problem
