### ISSUE TITLE
 error while trying to install s3 service 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [Jumpscale/digital_me#19]
got this error while trying to install s3 service 

#### Steps to reproduce
```python
data = {
'farmerIyoOrg': '<>',
 'minioLogin': '<>',
 'minioPassword': '<>',
 'storageSize': 2,
 'storageType': 'hdd',
 'vmZerotier': {'id': '<>', 'ztClient': 'main'}
}

s3 = robot.services.create('github.com/jumpscale/digital_me/s3/0.0.1','s13', data)
s3.schedule_action('install').wait()
```

#### Relevant stacktraces
```
[Thu28 11:00] - base.py           :209 :service-fed98911-ddcb-489f-bfd1-40a3ca632657 - ERROR    - error executing ac
tion install:
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-templates/templates/vm/vm.py", line 65, in install
    vm_sal = self._vm_sal
  File "/opt/code/github/zero-os/0-templates/templates/vm/vm.py", line 26, in _vm_sal
    return self._node_sal.primitives.from_dict('vm', data)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/primitives.py", line 155, in from_dict
    vm.from_dict(data)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/VM.py", line 611, in from_dict
    super().from_dict(data)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/VM.py", line 473, in from_dict
    self.disks.add(disk['name'], disk['url'], disk.get('mountPoint'), disk.get('filesystem'))
KeyError: 'url'
```

**Comment by serboctor** [comment]
@ahmedelsayed-93 tested it again against nodes with updated repos and couldn't reproduce it.
