### ISSUE TITLE
uninstall/re-install VM doesn't work

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/digital_me#22]
I'm creating a vm :
```python
data = {
    'nodeId': '544546f60261',
    'memory': 512,
    'disks': [{
        'diskType': 'hdd',
        'size': 10,
        'mountPoint': '/mnt',
        'filesystem': 'btrfs',
        'label': 'test',
    }],
    'zerotier': {'id': '12ac4a1e716b16cc', 'ztClient': 'ztDev'},
    'image': 'ubuntu',
    'configs': [{'path': '/root/.ssh/authorized_keys', 'content': SSH_PUB, 'name': 'sshkey'}]
}
vm = robot.services.create('github.com/jumpscale/digital_me/vm/0.0.1', 'vm1', data)
t = vm.schedule_action('install')
```

everything works fine, the VM is created and I can ssh into it.
Then I uninstall the vm 
```
t = vm.schedule_action('uninstall')
```
Uninstall works well too.
Then I try to re-install the same VM service.
`t = vm.schedule_action('install')`

and there I get this error:

```
Out[6]: Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-templates/templates/zerodb/zerodb.py", line 61, in install
    self._deploy()
  File "/opt/code/github/zero-os/0-templates/templates/zerodb/zerodb.py", line 35, in _deploy
    zerodb_sal.deploy()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/zerodb/zerodb.py", line 259, in deploy
    live_namespaces = self._live_namespaces()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/zerodb/zerodb.py", line 352, in _live_namespaces
    result = self._redis.execute_command('NSLIST')
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 493, in connect
    self.on_connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 561, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: Access denied
Access denied
```

**Comment by zaibon** [comment]
This bug also happens when I try to install 2 VMs. the first one always works, but the second create the same `Access denied` error.

We narrowed down the problem to the redis connection that's supposed to talk to the 0-db to create the namespace on it. For some reason only the first zerodb created works.

**Comment by zaibon** [comment]
seems the problem is also linked with the fact that we try to connect from withint the node robot container.
I tried to authenticate to the same 0-db from the host and from the node robot container and got 2 different responses:

from the host
```shell
redis-cli -h 172.18.0.6 -p 9900 auth bucr5unxduq8397funw6n8qna
OK
````

from within the node robot container:
```
redis-cli -h 172.18.0.6 -p 9900 auth bucr5unxduq8397funw6n8qna
OK
```
