### ISSUE TITLE
VM Uninstall action => AttributeError

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/digital_me#31]
```
vm1_service = robot.services.get(name='myfirstvm')
t = vm1_service.schedule_action('uninstall')
```

Traceback:
```
NameError: name 'eco' is not defined
In [600]: t.eco
Out[600]: Traceback (most recent call last):
  File "/Users/yves/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/Users/yves/code/github/jumpscale/digital_me/templates/vm/vm.py", line 140, in uninstall
    self._node_vm.schedule_action('uninstall').wait(die=True)
  File "/Users/yves/code/github/jumpscale/digital_me/templates/vm/vm.py", line 54, in _node_vm
    return self._node_api.services.get(name=self.guid)
AttributeError: 'NoneType' object has no attribute 'services'
'NoneType' object has no attribute 'services'
```

**Comment by zaibon** [comment]
Do you have any more info about how you end up in this situation cause from the code it sees it is impossible to have `self._node_api` to be None. Which make me think this is maybe caused by a bug in the 0-robot itself

**Comment by yveskerwyn** [comment]
Closing since I was unable to reproduce
