### ISSUE TITLE
Installing GW is creating a ztclient with empty token

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/digital_me#32]
```python
gw_data = {'domain': 'lan',
 'hostname': 'mygw',
 'networks': [{'id': '8850338390729392',
   'name': 'private',
   'public': False,
   'type': 'zerotier',
   'ztClient': 'newWorker2'}],
 'nodeId': '525400000521',
 'portforwards': [{'dstport': 22,
   'name': 'pf',
   'protocols': ['tcp'],
   'srcport': 22022,
   'vm': 'vm00100000000100010'}]}

dmgw_1 = robot.services.create('github.com/jumpscale/digital_me/gateway/0.0.1', service_name='dm_gw_6', data=gw_data)

dmgw_1.schedule_action('install').wait(die=True)
```

**Actual result**
```bash
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/jumpscale/digital_me/templates/gateway/gateway.py", line 84, in install
    self._update_portforwards(gwservice, pgwservice)
  File "/opt/code/github/jumpscale/digital_me/templates/gateway/gateway.py", line 133, in _update_portforwards
    vmips[vmname] = self._get_vm_ip(vmname)
  File "/opt/code/github/jumpscale/digital_me/templates/gateway/gateway.py", line 237, in _get_vm_ip
    zcl = j.clients.zerotier.get(info['zerotier']['ztClient'], interactive=False)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/JSBaseClassConfigs.py", line 43, in get
    return self._child_class(instance=instance, data=data, parent=self, interactive=interactive,**kwargs)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zerotier/ZerotierClient.py", line 278, in __init__
    raise RuntimeError("Missing auth token in config instance {}".format(instance))
RuntimeError: Missing auth token in config instance 5ed4c2f3-96d4-4c7e-a026-5bdfa1facf2a
---------------------------------------------------------------------------
ErrorConditionObject                      Traceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 dmgw_1.schedule_action('install').wait(die=True)

/opt/code/github/zero-os/0-robot/zerorobot/task/task.py in wait(self, timeout, die)
    129                 logger.critical('task is in error state, but no eco')
    130             else:
--> 131                 raise self.eco
    132 
    133         return self

ErrorConditionObject: Missing auth token in config instance 5ed4c2f3-96d4-4c7e-a026-5bdfa1facf2a
```

![image](https://user-images.githubusercontent.com/17981089/42327552-489b3c72-806c-11e8-8954-5620d700faea.png)

**Env**
zOS: 1.4.1
0-robot: development
0-dm: master
0-template: developmet
js9: dev

**Comment by zaibon** [comment]
@islamTaha12 I need to see how you created the zerotier client in the fist place. Cause in you description I don't know if the zerotier client is not already wrong before you install the gateway

**Comment by yveskerwyn** [comment]
@zaibon also see my ticket: https://github.com/Jumpscale/digital_me/issues/30

And here's the script with all the steps: https://github.com/yveskerwyn/bettertoken/blob/master/digital_me.md

**Comment by yveskerwyn** [comment]
@zaibon: https://github.com/yveskerwyn/bettertoken/blob/master/digital_me.md#create-client-service

**Comment by islamTaha12** [comment]
@zaibon 
here is how I create the ztClient
```
robot.services.create('github.com/zero-os/0-templates/zerotier_client/0.0.1', 'newWorker2', data={'token':MYTOKEN})
```

and I used it while I'm `installing` the VM, and it works fine.

**Comment by islamTaha12** [comment]
I can confirm GW with the following data is working fine
```
In [39]: gw_data
Out[39]: 
{'domain': 'lan',
 'hostname': 'mygw',
 'networks': [{'id': 'e4da7455b25840e8',
   'name': 'private',
   'public': False,
   'type': 'zerotier',
   'ztClient': 'newWorker2'}],
 'nodeId': '5254000005f9',
 'portforwards': [{'dstport': 22,
   'name': 'pf',
   'protocols': ['tcp'],
   'srcport': 22022,
   'vm': 'vm_1'}]}
```

and I can access the vm via the public_ip
