### ISSUE TITLE
"'NoneType' object has no attribute 'services'" when scheduling `add_http_proxy` action of DM GW

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/digital_me#37]
Reproduce:
```python
gw_hostname = '...'
node_id = '...'
zt_private_network_id = '...'
DM_GW_UID = 'github.com/jumpscale/digital_me/gateway/0.0.1'
gw_hostname = 'mygw'
gw_data = {
    'hostname': gw_hostname,
    'domain': 'lan',
    'nodeId': node_id,
    'networks': [{
        'name': 'private',
        'type': 'zerotier',
        'public': False,
        'id': zt_private_network_id,
        'ztClient': dm_zt_client_service_name
    }],
}

dm_gw_service = dm_robot.services.create(template_uid=DM_GW_UID, service_name='dm_gw', data=gw_data)
task = dm_gw_service.schedule_action('install').wait()
proxy_name = 'myproxy'
vm_name = 'vm1'
proxy_cfg = {'name': proxy_name, 'host': vm_zt_ip_addr, 'types': ['http'], 'destinations': [{'vm': vm_name, 'port': 8000}]}
proxy_cfg
dm_gw_service.schedule_action(action='add_http_proxy', args={'proxy': proxy_cfg}).wait(die=True)
```

Traceback:
```python
Traceback (most recent call last):
  File "/Users/yves/code/github/zero-os/0-robot/zerorobot/task/task.py", line 77, in execute
    self._result = self._func(**self._args)
  File "/Users/yves/code/github/jumpscale/digital_me/templates/vm/vm.py", line 167, in info
    info = self._node_vm.schedule_action('info', args={'timeout': timeout}).wait(die=True).result
  File "/Users/yves/code/github/jumpscale/digital_me/templates/vm/vm.py", line 54, in _node_vm
    return self._node_api.services.get(name=self.guid)
AttributeError: 'NoneType' object has no attribute 'services'
---------------------------------------------------------------------------
ErrorConditionObject                      Traceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 dm_gw_service.schedule_action(action='add_http_proxy', args={'proxy': proxy_cfg}).wait(die=True)

~/code/github/zero-os/0-robot/zerorobot/task/task.py in wait(self, timeout, die)
    129                 logger.critical('task is in error state, but no eco')
    130             else:
--> 131                 raise self.eco
    132
    133         return self

ErrorConditionObject: 'NoneType' object has no attribute 'services'
```

**Comment by zaibon** [comment]
Here is how I tried to reproduce:
- install a GW and a VM
- stop/start DM robot
- stop/start zero-os node
- add http proxy: succeed
- remove http proxy: succeed

So I can't really reproduce this

**Comment by yveskerwyn** [comment]
@zaibon did you try on a node, or locally?

**Comment by yveskerwyn** [comment]
Here are all steps: https://github.com/yveskerwyn/bettertoken/blob/master/digital_me.md#public-gw

I can retry of course for 10th time, but I always get into the same problem, so perfectly reproducealbe...

I will try on another new node later this afternoon...

**Comment by yveskerwyn** [comment]
Still not working for me, will try from another JS env

**Comment by yveskerwyn** [comment]
Also when trying to uninstall the service I get the same error:

![screen shot 2018-07-11 at 17 07 18](https://user-images.githubusercontent.com/13795109/42581499-25d49128-852d-11e8-8026-868be556fa20.png)

**Comment by yveskerwyn** [comment]
got it working
