### ISSUE TITLE
can't create a machine with vdisk size > real disk size

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/digital_me#42]
**Description**
I have a zos machine which has 3 hdd disks (10, 50, 50) and the grid registered it with 110 HRU
![image](https://user-images.githubusercontent.com/17981089/43356317-b2771508-926e-11e8-86dc-c7acbc0ad23f.png)

I tried to create a VM with vdisk size = 90G which should be deployed using two disks

**steps**
```python
In [45]: data = {
    ...:  'nodeId': '52540000066f',
    ...:  'disks': [{
    ...:          'diskType': 'hdd',
    ...:          'size': 90,
    ...:          'mountPoint': '/mnt',
    ...:          'filesystem': 'btrfs',
    ...:          'label': 'xtremx'
    ...:      }],
    ...:  'image': 'ubuntu',
    ...:  'memory': 2048,
    ...:  'cpu':2,
    ...:  'zerotier': {'id':'1c33c1ced0f00852', 'ztClient': 'newWorker'},
    ...:  'configs': [{'path': '/root/.ssh/authorized_keys', 'content': mykey, 'name': 'sshkey'}]
    ...:  }
    ...:  

In [46]: vmservice = robot.services.create('github.com/jumpscale/digital_me/vm/0.0.1', service_name='vm050', data=data)

In [47]: vmservice.schedule_action('install').wait(die=True)
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 77, in execute
    self._result = self._func(**self._args)
  File "/opt/code/github/zero-os/0-templates/templates/node/node.py", line 222, in create_zdb_namespace
    raise NoNamespaceAvailability(message)
node.NoNamespaceAvailability: Not enough free space for namespace creation with size 90 and type HDD,ARCHIVE
---------------------------------------------------------------------------
ErrorConditionObject                      Traceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 vmservice.schedule_action('install').wait(die=True)

/opt/code/github/zero-os/0-robot/zerorobot/task/task.py in wait(self, timeout, die)
    129                 logger.critical('task is in error state, but no eco')
    130             else:
--> 131                 raise self.eco
    132 
    133         return self

ErrorConditionObject: Not enough free space for namespace creation with size 90 and type HDD,ARCHIVE
```

**Env**
zos : 1.4.1
js9 : development

**Comment by zaibon** [comment]
0-db doesn't support this feature. At the moment a vdisk can have a maximum size equal to the size of the physical disk used underneath
